#This file stores configuration options for Iris, such as the currently active shaderpack
#Thu Jul 30 15:56:39 BRT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=
