#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Aug 04 10:43:28 BRT 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=true
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=12
shaderPack=
